site_name: Tự đi mà ôn thi (ngoại ngữ)
site_description: Tự học ngoại ngữ, hết.
site_author: duykhanh471
repo_url: https://github.com/daihocmo/luyen-thi-ngon-ngu
repo_name: Ôn luyện ngoại ngữ

nav:
  - 'Trang chủ': 'index.md'
  - 'Tiếng Anh':
    - 'Hướng dẫn ôn thi': 'tieng-anh/huong-dan-on-thi.md'
    - 'Mục lục': 'tieng-anh/README.md'
    - '20 quy tắc ngữ pháp': 'tieng-anh/ngu-phap/20-quy-tac-ngu-phap.md'
    - 'Ngữ pháp cấp độ từ':
        - 'Tìm hiểu cơ bản về 9 từ loại trong Tiếng Anh': 'tieng-anh/ngu-phap/word-level/parts-of-speech.md'
        - 'Động từ và thì động từ':
          - 'Hướng dẫn chính': 'tieng-anh/ngu-phap/word-level/dong-tu/README.md'
          - 'Thì hiện tại':
              - 'Đơn': 'tieng-anh/ngu-phap/word-level/dong-tu/hien-tai-don.md'
              - 'Tiếp diễn': 'tieng-anh/ngu-phap/word-level/dong-tu/hien-tai-tiep-dien.md'
              - 'Hoàn thành': 'tieng-anh/ngu-phap/word-level/dong-tu/hien-tai-hoan-thanh.md'
              - 'Hoàn thành tiếp diễn': 'tieng-anh/ngu-phap/word-level/dong-tu/hien-tai-hoan-thanh-tiep-dien.md'
          - 'Thì quá khứ':
              - 'Đơn': 'tieng-anh/ngu-phap/word-level/dong-tu/qua-khu-don'
              - 'Tiếp diễn': 'tieng-anh/ngu-phap/word-level/dong-tu/qua-khu-tiep-dien.md'
              - 'Hoàn thành': 'tieng-anh/ngu-phap/word-level/dong-tu/qua-khu-hoan-thanh.md'
              - 'Hoàn thành tiếp diễn': 'tieng-anh/ngu-phap/word-level/dong-tu/qua-khu-hoan-thanh-tiep-dien.md'
          - 'Thì tương lai': 
              - 'Đơn': 'tieng-anh/ngu-phap/word-level/dong-tu/tuong-lai-don.md'
              - 'Tiếp diễn': 'tieng-anh/ngu-phap/word-level/dong-tu/tuong-lai-tiep-dien.md'
              - 'Hoàn thành': 'tieng-anh/ngu-phap/word-level/dong-tu/tuong-lai-hoan-thanh.md'
              - 'Hoàn thành tiếp diễn': 'tieng-anh/ngu-phap/word-level/dong-tu/tuong-lai-hoan-thanh-tiep-dien.md'
          - 'going to': 'tieng-anh/ngu-phap/word-level/dong-tu/going-to.md'
          - 'about to': 'tieng-anh/ngu-phap/word-level/dong-tu/about-to.md'
          - 'for và since': 'tieng-anh/ngu-phap/word-level/dong-tu/for-va-since.md'
          - 'Subjunctive Mood': 'tieng-anh/ngu-phap/word-level/dong-tu/subjunctive-mood.md' 
          - 'Dạng bị động': 'tieng-anh/ngu-phap/word-level/dong-tu/chu-dong-bi-dong.md'
          - 'be used to/used to do': 'tieng-anh/ngu-phap/word-level/dong-tu/used-to.md'
          - 'Future Time': 'tieng-anh/ngu-phap/word-level/dong-tu/future-time.md'
          - 'Câu điều kiện':
            - 'Bản chất của câu điều kiện': 'tieng-anh/ngu-phap/word-level/dong-tu/ban-chat-cau-dieu-kien.md'
            - 'Các loại câu điều kiện': 'tieng-anh/ngu-phap/word-level/dong-tu/cau-dieu-kien.md'
            - Thì của động từ trong câu điều kiện
            - 'Những cách khác để diễn tả câu điều kiện': 'tieng-anh/ngu-phap/word-level/dong-tu/nhung-cach-khac-if.md'
          - 'Động từ khuyết thiếu': 'tieng-anh/ngu-phap/word-level/dong-tu/dong-tu-khuyet-thieu.md'
          - 'Phrasal Verbs cơ bản': 'tieng-anh/ngu-phap/word-level/dong-tu/phrasal-verb-co-ban.md'
          - 'Câu hỏi': 'tieng-anh/ngu-phap/word-level/dong-tu/cau-hoi.md' 
          - 'Câu hỏi đuôi - Tag Questions': 'tieng-anh/ngu-phap/word-level/dong-tu/cau-hoi-duoi.md'
          - 'Hòa hợp chủ ngữ - động từ': 'tieng-anh/ngu-phap/word-level/dong-tu/s-v-argreement.md'
          - 'Thể sai khiến': 'tieng-anh/ngu-phap/word-level/dong-tu/the-sai-khien.md'
        - 'Danh từ': 'tieng-anh/ngu-phap/word-level/danh-tu/README.md'
        - 'Tính từ': 'tieng-anh/ngu-phap/word-level/tinh-tu/README.md'
        - 'Trạng từ': 'tieng-anh/ngu-phap/word-level/trang-tu/README.md'
        - 'Từ hạn định': 'tieng-anh/ngu-phap/word-level/tu-han-dinh/README.md'
        - 'Giới từ': 'tieng-anh/ngu-phap/word-level/gioi-tu/README.md'
        - 'Đại từ': 'tieng-anh/ngu-phap/word-level/dai-tu/README.md'
        - 'Liên từ': 'tieng-anh/ngu-phap/word-level/lien-tu/README.md'
        - 'Thán từ': 'tieng-anh/ngu-phap/word-level/than-tu/README.md'
    - 'Ngữ pháp cấp độ câu':
        - 'Phân biệt Phrase, Clause và Sentence': 'tieng-anh/ngu-phap/sentence-level/phrase-clause-sentence.md' 
        - 'Cụm từ & Mệnh đề':
            - 'Cụm từ trong Tiếng Anh': 'tieng-anh/ngu-phap/sentence-level/grammatical-phrases.md'
            - 'Mệnh đề độc lập và phụ thuộc': 'tieng-anh/ngu-phap/sentence-level/menh-de-doc-lap-phu-thuoc.md'
            - 'Mệnh đề danh từ': 'tieng-anh/ngu-phap/sentence-level/menh-de/menh-de-danh-tu.md'
            - 'Mệnh đề quan hệ': 'tieng-anh/ngu-phap/sentence-level/menh-de/menh-de-quan-he.md'
            - 'Mệnh đề trạng từ': 'tieng-anh/ngu-phap/sentence-level/menh-de/menh-de-trang-tu.md'
        - 'Câu trong Tiếng Anh': 'tieng-anh/ngu-phap/sentence-level/cau-trong-tieng-anh-la-gi.md'
        - 'Bốn kiểu câu & Bốn kiểu cấu trúc câu': 'tieng-anh/ngu-phap/sentence-level/loai-cau.md'
        - 'Linking, Intransitive và Transitive Verbs':
            - 'Nội động từ và ngoại động từ': 'tieng-anh/ngu-phap/sentence-level/noi-dong-tu-ngoai-dong-tu.md' 
            - 'Linking verbs': 'tieng-anh/ngu-phap/sentence-level/linking-verb.md'
        - 'Direct Object và Indirect Object': 'tieng-anh/ngu-phap/sentence-level/tan-ngu.md'
        - 'Trạng từ liên kết - Conjunctive Adverbs': 'tieng-anh/ngu-phap/sentence-level/trang-tu-lien-ket.md'
        - 'Reported Speech': 'tieng-anh/ngu-phap/sentence-level/loi-noi-truc-tiep-va-gian-tiep.md'
        - 'Các danh mục ngữ pháp khác': 'tieng-anh/ngu-phap/sentence-level/cac-chu-de-ngu-phap-khac.md'
        - 'Những phần khác liên quan đến câu':
            - 'Punctuation': 'tieng-anh/ngu-phap/sentence-level/punctuation.md'
            - 'Capitalization': 'tieng-anh/ngu-phap/sentence-level/capitalization.md'
  - 'Tiếng Nhật':
    - 'Mục lục': 'tieng-nhat/README.md'
    - 'Khởi điểm': 'tieng-nhat/moi-bat-dau/huong-dan-chinh.md'
    - 'N5': 'tieng-nhat/n5/README.md'
    - 'N4': 'tieng-nhat/n4/README.md'
    - 'N3': 'tieng-nhat/n3/README.md'
    - 'N2': 'tieng-nhat/n2/README.md'
    - 'N1': 'tieng-nhat/n1/README.md'
  - 'Tiếng Trung': 'tieng-trung/README.md'
  - 'Tiếng Hàn': 'tieng-han/README.md'
  - 'Vietnamese':
    - 'Simple Vietnamese Grammar Guide': 'tieng-viet/simple-vietnamese-grammar-guide.md'
    - 'Dictionary Of Vietnamese Grammar': 'tieng-viet/dictionary-of-vietnamese-grammar.md'



theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
  language: vi
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep-purple
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode    
      primary: deep-purple

extra:
  generator: false

plugins:
  - search
  # - open-in-new-tab